//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicNS {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Text;
    
    
    public class dynamicClass {
        
        public void setValues(object obj) {
            personClass.Person dllClass = new personClass.Person();
            dllClass = ((personClass.Person)(obj));
            dllClass.name = "ff";
            dllClass.age = 31;
            dllClass.money = 11D;
            dllClass.isMan = true;
            dllClass.career[0] = "dd";
            dllClass.career[1] = "gg";
            dllClass.career[2] = "hh";
        }
    }
}
